 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/filled_surveys", type: :request do
  
  # FilledSurvey. As you add validations to FilledSurvey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FilledSurvey.create! valid_attributes
      get filled_surveys_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      filled_survey = FilledSurvey.create! valid_attributes
      get filled_survey_url(filled_survey)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_filled_survey_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      filled_survey = FilledSurvey.create! valid_attributes
      get edit_filled_survey_url(filled_survey)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FilledSurvey" do
        expect {
          post filled_surveys_url, params: { filled_survey: valid_attributes }
        }.to change(FilledSurvey, :count).by(1)
      end

      it "redirects to the created filled_survey" do
        post filled_surveys_url, params: { filled_survey: valid_attributes }
        expect(response).to redirect_to(filled_survey_url(FilledSurvey.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FilledSurvey" do
        expect {
          post filled_surveys_url, params: { filled_survey: invalid_attributes }
        }.to change(FilledSurvey, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post filled_surveys_url, params: { filled_survey: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested filled_survey" do
        filled_survey = FilledSurvey.create! valid_attributes
        patch filled_survey_url(filled_survey), params: { filled_survey: new_attributes }
        filled_survey.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the filled_survey" do
        filled_survey = FilledSurvey.create! valid_attributes
        patch filled_survey_url(filled_survey), params: { filled_survey: new_attributes }
        filled_survey.reload
        expect(response).to redirect_to(filled_survey_url(filled_survey))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        filled_survey = FilledSurvey.create! valid_attributes
        patch filled_survey_url(filled_survey), params: { filled_survey: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested filled_survey" do
      filled_survey = FilledSurvey.create! valid_attributes
      expect {
        delete filled_survey_url(filled_survey)
      }.to change(FilledSurvey, :count).by(-1)
    end

    it "redirects to the filled_surveys list" do
      filled_survey = FilledSurvey.create! valid_attributes
      delete filled_survey_url(filled_survey)
      expect(response).to redirect_to(filled_surveys_url)
    end
  end
end
