 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/question_options", type: :request do
  
  # QuestionOption. As you add validations to QuestionOption, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      QuestionOption.create! valid_attributes
      get question_options_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      question_option = QuestionOption.create! valid_attributes
      get question_option_url(question_option)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_question_option_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      question_option = QuestionOption.create! valid_attributes
      get edit_question_option_url(question_option)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new QuestionOption" do
        expect {
          post question_options_url, params: { question_option: valid_attributes }
        }.to change(QuestionOption, :count).by(1)
      end

      it "redirects to the created question_option" do
        post question_options_url, params: { question_option: valid_attributes }
        expect(response).to redirect_to(question_option_url(QuestionOption.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new QuestionOption" do
        expect {
          post question_options_url, params: { question_option: invalid_attributes }
        }.to change(QuestionOption, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post question_options_url, params: { question_option: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested question_option" do
        question_option = QuestionOption.create! valid_attributes
        patch question_option_url(question_option), params: { question_option: new_attributes }
        question_option.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the question_option" do
        question_option = QuestionOption.create! valid_attributes
        patch question_option_url(question_option), params: { question_option: new_attributes }
        question_option.reload
        expect(response).to redirect_to(question_option_url(question_option))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        question_option = QuestionOption.create! valid_attributes
        patch question_option_url(question_option), params: { question_option: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested question_option" do
      question_option = QuestionOption.create! valid_attributes
      expect {
        delete question_option_url(question_option)
      }.to change(QuestionOption, :count).by(-1)
    end

    it "redirects to the question_options list" do
      question_option = QuestionOption.create! valid_attributes
      delete question_option_url(question_option)
      expect(response).to redirect_to(question_options_url)
    end
  end
end
