test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:access_key_id] if Rails.application.credentials[Rails.env.to_sym][:aws]%>
  secret_access_key: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:secret_access_key] if Rails.application.credentials[Rails.env.to_sym][:aws] %>
  region: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:S3_REGION] if Rails.application.credentials[Rails.env.to_sym][:aws] %>
  bucket: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:S3_BUCKET] if Rails.application.credentials[Rails.env.to_sym][:aws] %>
