puts 'Creating WSS Survey'

questions = ['Czy osiągasz stałe, opodatkowane dochody?',
             'Czy przywiązujesz dużą wagę do faktu, żeposiadanie konopi jest w Polsce nielegalne?',
             'Czy używasz konopi w ilości większej niż 5gmiesięcznie?',
             'Czy używałeś kiedykolwiek konopi w miejscachpublicznych?',
             'Czy używałeś kiedykolwiek konopi w miejscupracy lub nauki?',
             'Czy kiedykolwiek świadomie udzieliłeś konopinieletniemu?',
             'Czy kiedykolwiek świadomie udzieliłeś konopidorosłemu który używał po raz pierwszy?',
             'Czy kiedykolwiek świadomie udzieliłeś konopidorosłemu który już wcześniej używał konopi?',
             'Czy kiedykolwiek czerpałeś korzyść majątkową zudzielenia komuś konopi?',
             'Czy bierzesz czynny udział w życiu społecznym(wybory, media,akcje)?',
             'Czy działasz w organizacjachrządowych/państwowych (służby, ośrodki,instytuty...) lub je wspomagasz?',
             'Czy działasz w organizacjach pozarządowych(stowarzyszenia,fundacje...) lub je wspomagasz?',
             'Czy w Twoim bliskim środowisku zażywaniekonopi jest tolerowane?',
             'Czy wśród członków Twojej rodziny zażywaniekonopi jest tolerowane?',
             'Czy uważasz, że jesteś uzależniony od konopi?',
             'Czy leczysz się lub leczyłeś się z powodunadmiernego zażywania konopi?',
             'Czy konopie zażywasz tylko rekreacyjnie?',
             'Czy byłeś karany w związku z konopiami?',
             'Czy popełniłeś kiedykolwiek czyn zabroniony wzwiązku z używaniem konopi (poza przypadkamiposiadania na własny np. kradzież, włamanie,pobicie...)?']
