name: Staging Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cannabishouse-staging"
          heroku_email: "konradrycerz@gmail.com"
          healthcheck: "https://cannabishouse-staging.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          delay: 10