name: Main
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - prod

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby 3.0.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundler: default
        bundler-cache: true
    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - name: Build and create DB
      env:
        # PGHOST: localhost
        # PGUSER: postgres
        # PGPORT: 5432
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/test
        # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        PG_USER: postgres
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bin/rails db:setup
    - name: Run tests
      env:
        # PGHOST: localhost
        # PGUSER: postgres
        # PGPORT: 5432
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/test
        # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        PG_USER: postgres
      run: |
        bundle exec rspec spec